/******************************************************************************
 *  Copyright (c) 2008 - 2010 IBM Corporation and others.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 * 
 *  Contributors:
 *    David Ungar, IBM Research - Initial Implementation
 *    Sam Adams, IBM Research - Initial Implementation
 *    Stefan Marr, Vrije Universiteit Brussel - Port to x86 Multi-Core Systems
 ******************************************************************************/

/** 
  Adapted version of the file that used to be sqr_config.h
  
  This is a file which is supposed to be generated by the Squeak build system,
  however, for the RoarVM, we avoid the trouble and hardcode the settings for
  our supported platforms here.
 
  File has been moved from the 'from_squeak' code into the RoarVM code base,
  to simplify synchronization with the upstream code.
 **/

#ifndef __sq_config_h
#define __sq_config_h


# if On_Apple
# define DARWIN 1
# endif

/* explicit image width */
# define	HAVE_INTERP_H 1

# if !Configure_Squeak_Code_for_Tilera
# define	USE_X11_GLX 1
# define	USE_QUARTZ 1
# define	USE_QUARTZ_CGL 1
# endif

# define	HAVE_LIBXEXT 1

# if Configure_Squeak_Code_for_Tilera
# define HAVE_LIBDL
# endif

# if Configure_Squeak_Code_for_Tilera
# undef   HAVE_DYLD
# else
# define	HAVE_DYLD 1
# endif

/* header files */
# define	HAVE_UNISTD_H 1
# define	HAVE_DIRENT_H 1
# define	HAVE_DLFCN_H 1

# if !Configure_Squeak_Code_for_Tilera
# define	HAVE_ICONV_H 1
# endif

# define	HAVE_SYS_TIME_H 1
# define	TIME_WITH_SYS_TIME 1
# define	HAVE_SYS_FILIO_H 1
# define	HAVE_UTIL_H 1

# if !Configure_Squeak_Code_for_Tilera
# define	HAVE_GL_GL_H 1
# define	HAVE_OPENGL_GL_H 1
# endif

/* system calls/library functions */
# define	AT_EXIT atexit
# define	HAVE_TZSET 1
# define	HAVE_OPENPTY 1
# define	HAVE_SNPRINTF 1
# define	HAVE_MMAP 1
# define	HAVE_LANGINFO_CODESET 1
# define	HAVE_ALLOCA 1
# define	HAVE_ALLOCA_H 1
# define	HAVE_UNSETENV 1

/* widths of primitive types */
# define	SIZEOF_INT 4
# define	SIZEOF_LONG 4
# define	SIZEOF_LONG_LONG 8
# define	SIZEOF_VOID_P 4

/* structures */
# define	HAVE_TM_GMTOFF 1
# define	HAVE_TIMEZONE 1

/* typedefs */
# define	squeakInt64 long long

/* architecture */
# define	OS_TYPE "unix"
# define	VM_HOST_CPU "i386"
# define	VM_HOST_OS "darwin9.2.2"
# define	VM_BUILD_STRING "Unix built on "__DATE__ " "__TIME__" Compiler: "__VERSION__
# define	DOUBLE_WORD_ORDER 1

/* other configured variables */
# define SQ_VERSION "3.9a-7021"
# define VM_VERSION "3.9-4"
# define VM_LIBDIR "/Users/ungar/renaissance/Squeak/vm/newVMbuild/lib/squeak/3.9-4"
# define VM_MODULE_PREFIX ""
# define VM_X11DIR "/usr/X11/lib"

#endif /* __sq_config_h */
